/**
* Fix EPCI to centre/route relation
*/
var ecpi2centre = {
    'pointe-medoc': [],
    'coeur-medoc': [],
    'centre-medoc': [],
    'lacs-medocains': [],
    'medulienne': ['medulienne', 'catelnau-medoc'],
    'estuaire': [],
    'medoc-estuaire': ['medoc-estuaire', 'arsac'],
    'canton-blaye': [],
    'saint-savin': ['saint-girons-aiguevives'],
    'canton-bourg': [],
    'cubzaguais': [],
    'canton-fronsac': [],
    'cali': ['smicval', 'saint-denis-pile'],
    'grand-saint-emilion': ['sictom-langonnais'],
    'castillon-pujols': ['smictom-castillon-la-bataille'],
    'pays-pelle': [],
    'brannais-entre-2-mers-ouest': [],
    'sauveterrois': ['massugas'],
    'canton-targon': [],
    'creonnais': ['saint-leon', 'smicotom'],
    'secteur-saint-loubes': [],
    'coteaux-bordelais': ['pompignac'],
    'cub': ['bordeaux-latule', 'saint-medard-en-jalles-touban'],
    'jalle-eau-bourde': ['saint-jean-illac', 'martignac-sur-jalle', 'cestas-canejan'],
    'coban': ['lege-cap-ferret', 'coban-atlantique'],
    'montesquieu': ['montesquieu'],
    'vallon-artolie': [],
    'canton-targon': [],
    'reolais-auros-monsegur': ['userctom-monsegur'],
    'coteaux-garonne': [],
    'coteaux-macariens': [],
    'canton-podensac': ['canton-podensac'],
    'cobas': ['cobas', 'teste-buch'],
    'val-eyre': ['val-eyre'],
    'sud-gironde': ['bazadais', 'captieux-grignols', 'fargues', 'pays-paroupian', 'sm-sauterrois'],
    'bazadais': []
}